title: Billy Price # The title of the blog
author: Billy Price # Your name 
email: billyprice98is@gmail.com # your email shown in the footer
url: billyprice.me # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  My personal webpage.
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: true # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  # avatar_url: "https://i.loli.net/2019/08/26/JzCLhDWPEybZr2T.jpg" # avatar in about page
  about_you: Student (Mathematics and Computer Science). # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.
  social_links:
    github:  billy-price
    twitter: Billy__Price

githubuser: "billy-price"

# Build settings
theme: huangyz0918/moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-remote-theme
  - jekyll-avatar
  - jekyll-feed
  - jekyll-seo-tag