title: Billy Price
description: Personal Website
email: billy.price@unimelb.edu.au
github_username:  billy-price


# Build settings
markdown: kramdown
remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5
font: Helvetica

plugins:
  - jekyll-paginate
  - jekyll-remote-theme